### PR TITLE
Update Giapi-tester to be able to read cmds from file

### PR DESCRIPTION
**Pull request by ekurz-gemini**
Change created for IGRINS2. Giapi-Tester will now be able to accept a the argument -file filename If the tester receive a file, it will iterate through each line in the file and execute each command. If it's not a file, the command will execute as expected. I also added in the possible "wait" function so that when executing commands in the file, you can add a wait in between them. The file would have a format similar to this:
-sc APPLY -activity PRESET -config "ig2:texp=10.0 ig2:svcimages=1" Wait 2

### CODE REVIEW

**Comment by cquiroz** [comment]
Thanks for the PR.

If I understand correctly the intent would be to support a batch of operations listed on a file so we could script a set of commands. Is that right? Will it be used to test scenarios with IGRINS2?

giapi-tester uses an internal mini library to parse arguments and act on them as seen here:
https://github.com/gemini-hlsw/gmp/blob/master/giapi-tester/src/main/java/edu/gemini/giapi/tool/GiapiTester.java#L32

Each possible parameter gets a class that will be able to interpret the argument. Given "-file" is a sort of meta argument perhaps it needs a slightly different behavior but I'd rather try to keep the same style.

The "Wait" method also uses a different style, it should probably be "-wait <number>" instead. Is it seconds?

Could you try following the existing approach and feel free to ask any questions if you encounter any difficulties.

**Comment by ekurz-gemini** [comment]
Yes, this will be used to test IGRINS2. I'll try to rewrite it following
the existing structure.

**Comment by ekurz-gemini** [comment]
Hi Carlos,

I was finally able to get around to writing the code in a way that
conformed to your structure. When you have some time, can you look it over
and see if it satisfies your requirements? Let me know if I need to change
anything.

Thanks,
Emma

**Review by cquiroz — APPROVED** [review]
Thanks a lot, we can merge once the test pass

**Comment by ekurz-gemini** [comment]
Sorry I was copying over these files from gitlab and made a typo with the giapi-tester when adding a line, I didn't notice until the failed build pointed it out. I've corrected that now. It passed the pipeline in gitlab, so it should pass the tests here now.

**Comment by ekurz-gemini** [comment]
Okay github is flagging some things that gitlab ignored. This is my first time actually working with Java so I'll take another look at it and try to fix these mistakes

**Comment by ekurz-gemini** [comment]
Hi Carlos,

I think all the tests are passing now. Could you take another look at this?

**Comment by cquiroz** [comment]
Thanks a lot this looks great

**Pull request merged**
